sudo:
 
services:
  - docker
  
before_install:
- docker pull ubuntu
- mkdir -p $TRAVIS_BUILD_DIR/codes
- cd $TRAVIS_BUILD_DIR/codes && git pull https://github.com/ly0/kendryte-standalone-sdk 

script:
- docker run -v $TRAVIS_BUILD_DIR/codes:/sdk ubuntu echo "hahaha"
